data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/FindBoat/Kaggle/blob/master/emc/data/TrainingData.csv
  raw_data_file: artifacts/data_ingestion/raw_data.csv
  train_data_file: artifacts/data_ingestion/train_data.csv
  test_data_file: artifacts/data_ingestion/test_data.csv
